server:
  port: 8003
spring:
  application:
    name: snack24-order
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/snack24_order
    username: root
    password: jinwoo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
logging:
  level:
    com.snack24.order: debug
