server:
  port: 8003
  shutdown: graceful
spring:
  application:
    name: snack24-order
  lifecycle:
    timeout-per-shutdown-phase: 25s
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/snack24_order
    username: root
    password: jinwoo
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: snack24-order
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: manual
    producer:
      acks: all
      properties:
        enable.idempotence: true
logging:
  level:
    com.snack24.order: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace
snack24:
  client:
    catalog:
      base-url: ${snack24.client.catalog.base-url:http://127.0.0.1:8002}
      connect-timeout: 1s
      read-timeout: 2s
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.snack24.order.controller
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${SPRING_PROFILES_ACTIVE:default}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: db,redis
        liveness:
          include: ping