server:
  port: 8001
spring:
  application:
    name: snack24-identity
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/snack24_identity
    username: root
    password: jinwoo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 2s
      lettuce:
        pool:
          max-active: 15
          max-idle: 8
          min-idle: 1
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
snack24:
  jwt:
    issuer: snack24-identity
    secret: ${SNACK24_JWT_SECRET:dGVzdC1zZWNyZXQtZm9yLWxvY2FsLW9ubHktMzItYnl0ZS1taW4=}
    access-token-validity: PT30M # 30분
    refresh-token-validity: P14D # 14일
logging:
  level:
    com.snack24.identity: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.snack24.identity