server:
  port: 8005
spring:
  application:
    name: snack24-notification-worker
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: snack24-notification-worker
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
