apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snack24

resources:
- ../../base

commonLabels:
  environment: dev

images:
- name: snack24/api-gateway
  newName: ghcr.io/jinwoo827/snack24/api-gateway
  newTag: 43b700e
- name: snack24/billing
  newName: ghcr.io/jinwoo827/snack24/billing
  newTag: 43b700e
- name: snack24/catalog
  newName: ghcr.io/jinwoo827/snack24/catalog
  newTag: 43b700e
- name: snack24/identity
  newName: ghcr.io/jinwoo827/snack24/identity
  newTag: 43b700e
- name: snack24/notification-worker
  newName: ghcr.io/jinwoo827/snack24/notification-worker
  newTag: 43b700e
- name: snack24/order
  newName: ghcr.io/jinwoo827/snack24/order
  newTag: 43b700e

patches:
- path: replicas-patch.yaml
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=snack24
- path: resources-patch.yaml
  target:
    kind: Deployment
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: snack24-gateway

configMapGenerator:
- literals:
  - SPRING_PROFILES_ACTIVE=dev
  - LOG_LEVEL=DEBUG
  name: app-env
