apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snack24

resources:
- ../../base
- hpa-order.yaml
- hpa-catalog.yaml

commonLabels:
  environment: prod

images:
- name: snack24/api-gateway
  newName: ghcr.io/jinwoo827/snack24/api-gateway
  newTag: f3ac664
- name: snack24/billing
  newName: ghcr.io/jinwoo827/snack24/billing
  newTag: f3ac664
- name: snack24/catalog
  newName: ghcr.io/jinwoo827/snack24/catalog
  newTag: f3ac664
- name: snack24/identity
  newName: ghcr.io/jinwoo827/snack24/identity
  newTag: f3ac664
- name: snack24/notification-worker
  newName: ghcr.io/jinwoo827/snack24/notification-worker
  newTag: f3ac664
- name: snack24/order
  newName: ghcr.io/jinwoo827/snack24/order
  newTag: f3ac664

patches:
- path: replicas-patch.yaml
  target:
    kind: Deployment
- path: resources-patch.yaml
  target:
    kind: Deployment
- path: imagepull-patch.yaml
  target:
    kind: Deployment
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: snack24-gateway

configMapGenerator:
- literals:
  - SPRING_PROFILES_ACTIVE=prod
  - LOG_LEVEL=INFO
  name: app-env
