server:
  port: 8000
  shutdown: graceful
spring:
  application:
    name: snack24-api-gateway
  lifecycle:
    timeout-per-shutdown-phase: 25s
  cloud:
    gateway:
      routes:
        - id: identity-auth
          uri: ${snack24.routes.identity-uri:http://127.0.0.1:8001}
          predicates:
            - Path=/v1/auth/**
        - id: identity-public-register
          uri: ${snack24.routes.identity-uri:http://127.0.0.1:8001}
          predicates:
            - Path=/v1/companies
            - Method=POST
        - id: identity-companies
          uri: ${snack24.routes.identity-uri:http://127.0.0.1:8001}
          predicates:
            - Path=/v1/companies/**
        - id: identity-members
          uri: ${snack24.routes.identity-uri:http://127.0.0.1:8001}
          predicates:
            - Path=/v1/members/**
        - id: catalog
          uri: ${snack24.routes.catalog-uri:http://127.0.0.1:8002}
          predicates:
            - Path=/v1/products/**
        - id: order
          uri: ${snack24.routes.order-uri:http://127.0.0.1:8003}
          predicates:
            - Path=/v1/orders/**
        - id: billing
          uri: ${snack24.routes.billing-uri:http://127.0.0.1:8004}
          predicates:
            - Path=/v1/wallets/**

snack24:
  gateway:
    permit-all-paths:
      - /v1/auth/**
      - POST:/v1/companies
      - /actuator/**
      - /v3/api-docs/**
  jwt:
    issuer: snack24-identity
    secret: ${SNACK24_JWT_SECRET:dGVzdC1zZWNyZXQtZm9yLWxvY2FsLW9ubHktMzItYnl0ZS1taW4=}
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.snack24.gateway: debug
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: ping